export const SECCIONES_CONTENIDO_SECURITY_DEF = {
  readAccess: 'SECCIONES_CONTENIDO_READ',
  updateAccess: 'SECCIONES_CONTENIDO_UPDATE',
  createAccess: 'SECCIONES_CONTENIDO_CREATE',
  deleteAccess: 'SECCIONES_CONTENIDO_DELETE'
};
