export const TEMPLATE_CONTENIDO_SECURITY_DEF = {
  readAccess: 'TEMPLATE_CONTENIDO_READ',
  updateAccess: 'TEMPLATE_CONTENIDO_UPDATE',
  createAccess: 'TEMPLATE_CONTENIDO_CREATE',
  deleteAccess: 'TEMPLATE_CONTENIDO_DELETE'
};
