export const VENTA_DERECHO_ANUAL_SECURITY_DEF = {
  readAccess: 'VENTA_DERECHO_ANUAL_READ',
  updateAccess: 'VENTA_DERECHO_ANUAL_UPDATE',
  createAccess: 'VENTA_DERECHO_ANUAL_CREATE',
  deleteAccess: 'VENTA_DERECHO_ANUAL_DELETE'
};
