name: Azure Static Web Apps CI/CD

pr:
  branches:
    include:
      - test
trigger:
  branches:
    include:
      - test

jobs:
- job: build_and_deploy_job
  displayName: Build and Deploy Job
  condition: or(eq(variables['Build.Reason'], 'Manual'),or(eq(variables['Build.Reason'], 'PullRequest'),eq(variables['Build.Reason'], 'IndividualCI')))
  pool:
    vmImage: ubuntu-latest
  variables:
  - group: Azure-Static-Web-Apps-black-mushroom-05da17c0f-variable-group
  steps:
  - checkout: self
    submodules: true
  - task: NodeTool@0
    inputs:
      versionSource: 'spec'
      versionSpec: '14.x'
  - script: |
      npm install -g @angular/cli@6.0.8
    displayName: 'install angular cli'
  - task: Npm@1
    displayName: 'npm install '
    inputs:
     workingDir: '$(System.DefaultWorkingDirectory)'
     verbose: false
  - task: Npm@1
    displayName: 'npm build'
    inputs:
        command: custom
        workingDir: '$(System.DefaultWorkingDirectory)'
        verbose: false
        customCommand: 'run build'
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'dist'
      ArtifactName: 'app'
      publishLocation: 'Container'
  - bash: cd $(Pipeline.Workspace); echo $(ls)
  - bash: cd $(Pipeline.Workspace)/app; echo $(ls)
  - task: AzureStaticWebApp@0
    inputs:
      azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN_BLACK_MUSHROOM_05DA17C0F)
      app_location: "/dist" # App source code path
      #api_location: "" # Api source code path - optional
      skip_app_build: true
      skip_api_build: true
      verbose: true
      cwd: '$(Pipeline.Workspace)'
      # app_build_command: "npm install -g @angular/cli@6.0.8 && npm install && ng build --env=test"
      # app_build_command: "npm install -g @angular/cli@6.0.8 && npm install --save-dev --unsafe-perm node-sass && npm install && ng build --env=test"
      #output_location: "dist" # Built app content directory - optional
  
