export const REVISTA_CONTENIDOS_SECURITY_DEF = {
  readAccess: 'RN_REVISTA_CONTENIDOS_READ',
  updateAccess: 'RN_REVISTA_CONTENIDOS_UPDATE',
  createAccess: 'RN_REVISTA_CONTENIDOS_CREATE',
  deleteAccess: 'RN_REVISTA_CONTENIDOS_DELETE'
};
