export const CONTENIDO_TAGS_SECURITY_DEF = {
  readAccess: 'RN_CONTENIDO_TAGS_READ',
  updateAccess: 'RN_CONTENIDO_TAGS_UPDATE',
  createAccess: 'RN_CONTENIDO_TAGS_CREATE',
  deleteAccess: 'RN_CONTENIDO_TAGS_DELETE'
};
