export const SECCION_BOLETIN_CONTENIDO_SECURITY_DEF = {
  readAccess: 'SECCION_BOLETIN_CONTENIDO_READ',
  updateAccess: 'SECCION_BOLETIN_CONTENIDO_UPDATE',
  createAccess: 'SECCION_BOLETIN_CONTENIDO_CREATE',
  deleteAccess: 'SECCION_BOLETIN_CONTENIDO_DELETE'
};
