export const PERFIL_MATRICULADO_SECURITY_DEF = {
  readAccess: 'PERFIL_MATRICULADO_READ',
  updateAccess: 'PERFIL_MATRICULADO_UPDATE',
  createAccess: 'PERFIL_MATRICULADO_CREATE',
  deleteAccess: 'PERFIL_MATRICULADO_DELETE'
};
