export const PERFIL_REDES_SOCIALES_SECURITY_DEF = {
  readAccess: 'PERFIL_REDES_SOCIALES_READ',
  updateAccess: 'PERFIL_REDES_SOCIALES_UPDATE',
  createAccess: 'PERFIL_REDES_SOCIALES_CREATE',
  deleteAccess: 'PERFIL_REDES_SOCIALES_DELETE'
};
