export const MESSAGE_TEMPLATE_HISTORY_SECURITY_DEF = {
  readAccess: 'MESSAGE_TEMPLATE_HISTORY_READ',
  updateAccess: 'MESSAGE_TEMPLATE_HISTORY_UPDATE',
  createAccess: 'MESSAGE_TEMPLATE_HISTORY_CREATE',
  deleteAccess: 'MESSAGE_TEMPLATE_HISTORY_DELETE'
};
