export const CONTENIDOS_HISTORY_SECURITY_DEF = {
  readAccess: 'CONTENIDOS_HISTORY_READ',
  updateAccess: 'CONTENIDOS_HISTORY_UPDATE',
  createAccess: 'CONTENIDOS_HISTORY_CREATE',
  deleteAccess: 'CONTENIDOS_HISTORY_DELETE'
};
