export const NOTICIA_CARROUSEL_HISTORY_SECURITY_DEF = {
  readAccess: 'NOTICIA_CARROUSEL_HISTORY_READ',
  updateAccess: 'NOTICIA_CARROUSEL_HISTORY_UPDATE',
  createAccess: 'NOTICIA_CARROUSEL_HISTORY_CREATE',
  deleteAccess: 'NOTICIA_CARROUSEL_HISTORY_DELETE'
};
