export const SECCIONES_HISTORY_SECURITY_DEF = {
  readAccess: 'SECCIONES_HISTORY_READ',
  updateAccess: 'SECCIONES_HISTORY_UPDATE',
  createAccess: 'SECCIONES_HISTORY_CREATE',
  deleteAccess: 'SECCIONES_HISTORY_DELETE'
};
