export const OPCION_SECURITY_DEF = {
  readAccess: 'FORMULARIO_CAMPOS_READ',
  updateAccess: 'FORMULARIO_CAMPOS_UPDATE',
  createAccess: 'FORMULARIO_CAMPOS_CREATE',
  deleteAccess: 'FORMULARIO_CAMPOS_DELETE'
};
