export const PERFIL_MATRICULADO_UPLOAD_SECURITY_DEF = {
    readAccess: 'PERFIL_MATRICULADO_UPLOAD_READ',
    updateAccess: 'PERFIL_MATRICULADO_UPLOAD_UPDATE',
    createAccess: 'PERFIL_MATRICULADO_UPLOAD_CREATE',
    deleteAccess: 'PERFIL_MATRICULADO_UPLOAD_DELETE'
  };
