export const PRODUCTO_EXTERNO_HISTORY_SECURITY_DEF = {
  readAccess: 'PRODUCTO_EXTERNO_HISTORY_READ',
  updateAccess: 'PRODUCTO_EXTERNO_HISTORY_UPDATE',
  createAccess: 'PRODUCTO_EXTERNO_HISTORY_CREATE',
  deleteAccess: 'PRODUCTO_EXTERNO_HISTORY_DELETE'
};
