export const CONTENIDO_HISTORY_SECURITY_DEF = {
  readAccess: 'CONTENIDO_HISTORY_READ',
  updateAccess: 'CONTENIDO_HISTORY_UPDATE',
  createAccess: 'CONTENIDO_HISTORY_CREATE',
  deleteAccess: 'CONTENIDO_HISTORY_DELETE'
};
