export const PERFIL_PUBLICACIONES_SECURITY_DEF = {
  readAccess: 'PERFIL_PUBLICACIONES_READ',
  updateAccess: 'PERFIL_PUBLICACIONES_UPDATE',
  createAccess: 'PERFIL_PUBLICACIONES_CREATE',
  deleteAccess: 'PERFIL_PUBLICACIONES_DELETE'
};
