export const CONTENIDO_AUTORES_SECURITY_DEF = {
  readAccess: 'CONTENIDO_AUTORES_READ',
  updateAccess: 'CONTENIDO_AUTORES_UPDATE',
  createAccess: 'CONTENIDO_AUTORES_CREATE',
  deleteAccess: 'CONTENIDO_AUTORES_DELETE'
};
