export const PERFIL_NEWSLETTERS_SECURITY_DEF = {
  readAccess: 'PERFIL_NEWSLETTERS_READ',
  updateAccess: 'PERFIL_NEWSLETTERS_UPDATE',
  createAccess: 'PERFIL_NEWSLETTERS_CREATE',
  deleteAccess: 'PERFIL_NEWSLETTERS_DELETE'
};
